# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9ac54226e649ff8e60daebf444ff6fa1bbcd3dc5a5c97e0d42bf2f959e98cebdb8fe142118648a3c6f6d7ccf67c2c459de564c3f6b3a0833794adaca315d4c2

test:
  secret_key_base: 1a2b604026bc5a94694ad429b56683d347a7e398a45b7bd98164b9755bd6531f2b89ede1efe2e9c54c7123cf45f35a42b902eb0a5b46c74621aba6b9cd80290a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
